
// Generated helper templates
// Generated items
// EduHub.Data\src\EduHub.Data\Entities\UM_TFR.cs
// EduHub.Data\src\EduHub.Data\Entities\UM_TFRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\UM.cs
// EduHub.Data\src\EduHub.Data\Entities\UMDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TXHG.cs
// EduHub.Data\src\EduHub.Data\Entities\TXHGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TXAS.cs
// EduHub.Data\src\EduHub.Data\Entities\TXASDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TTTG.cs
// EduHub.Data\src\EduHub.Data\Entities\TTTGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TTEX.cs
// EduHub.Data\src\EduHub.Data\Entities\TTEXDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TTES.cs
// EduHub.Data\src\EduHub.Data\Entities\TTESDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TTEP.cs
// EduHub.Data\src\EduHub.Data\Entities\TTEPDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TTEI.cs
// EduHub.Data\src\EduHub.Data\Entities\TTEIDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TTEF.cs
// EduHub.Data\src\EduHub.Data\Entities\TTEFDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TT.cs
// EduHub.Data\src\EduHub.Data\Entities\TTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TRSTACC.cs
// EduHub.Data\src\EduHub.Data\Entities\TRSTACCDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TRPROUT.cs
// EduHub.Data\src\EduHub.Data\Entities\TRPROUTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TRPMODE.cs
// EduHub.Data\src\EduHub.Data\Entities\TRPMODEDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\THTQ.cs
// EduHub.Data\src\EduHub.Data\Entities\THTQDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\THTN.cs
// EduHub.Data\src\EduHub.Data\Entities\THTNDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TH.cs
// EduHub.Data\src\EduHub.Data\Entities\THDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TETN.cs
// EduHub.Data\src\EduHub.Data\Entities\TETNDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TETE.cs
// EduHub.Data\src\EduHub.Data\Entities\TETEDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TEC.cs
// EduHub.Data\src\EduHub.Data\Entities\TECDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TE.cs
// EduHub.Data\src\EduHub.Data\Entities\TEDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TCTR.cs
// EduHub.Data\src\EduHub.Data\Entities\TCTRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TCTQ.cs
// EduHub.Data\src\EduHub.Data\Entities\TCTQDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TCTD.cs
// EduHub.Data\src\EduHub.Data\Entities\TCTDDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TCTB.cs
// EduHub.Data\src\EduHub.Data\Entities\TCTBDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TCAT.cs
// EduHub.Data\src\EduHub.Data\Entities\TCATDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TC.cs
// EduHub.Data\src\EduHub.Data\Entities\TCDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SXHI.cs
// EduHub.Data\src\EduHub.Data\Entities\SXHIDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SXAS.cs
// EduHub.Data\src\EduHub.Data\Entities\SXASDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SXABCONV.cs
// EduHub.Data\src\EduHub.Data\Entities\SXABCONVDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SXAB.cs
// EduHub.Data\src\EduHub.Data\Entities\SXABDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SVAG.cs
// EduHub.Data\src\EduHub.Data\Entities\SVAGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SUPR.cs
// EduHub.Data\src\EduHub.Data\Entities\SUPRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SUBL.cs
// EduHub.Data\src\EduHub.Data\Entities\SUBLDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SU.cs
// EduHub.Data\src\EduHub.Data\Entities\SUDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STVDO_TR.cs
// EduHub.Data\src\EduHub.Data\Entities\STVDO_TRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STVDO.cs
// EduHub.Data\src\EduHub.Data\Entities\STVDODataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STVDI_TR.cs
// EduHub.Data\src\EduHub.Data\Entities\STVDI_TRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STVDI.cs
// EduHub.Data\src\EduHub.Data\Entities\STVDIDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STTRIPS.cs
// EduHub.Data\src\EduHub.Data\Entities\STTRIPSDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STSUP_TR.cs
// EduHub.Data\src\EduHub.Data\Entities\STSUP_TRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STSUP.cs
// EduHub.Data\src\EduHub.Data\Entities\STSUPDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STSP.cs
// EduHub.Data\src\EduHub.Data\Entities\STSPDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STSB.cs
// EduHub.Data\src\EduHub.Data\Entities\STSBDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STRE.cs
// EduHub.Data\src\EduHub.Data\Entities\STREDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STRA.cs
// EduHub.Data\src\EduHub.Data\Entities\STRADataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STPT.cs
// EduHub.Data\src\EduHub.Data\Entities\STPTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STPS_TFR.cs
// EduHub.Data\src\EduHub.Data\Entities\STPS_TFRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STPS.cs
// EduHub.Data\src\EduHub.Data\Entities\STPSDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STPO.cs
// EduHub.Data\src\EduHub.Data\Entities\STPODataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STNAT_TR.cs
// EduHub.Data\src\EduHub.Data\Entities\STNAT_TRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STNAT.cs
// EduHub.Data\src\EduHub.Data\Entities\STNATDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STMB.cs
// EduHub.Data\src\EduHub.Data\Entities\STMBDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STMA.cs
// EduHub.Data\src\EduHub.Data\Entities\STMADataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STBT.cs
// EduHub.Data\src\EduHub.Data\Entities\STBTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STAR_TFR.cs
// EduHub.Data\src\EduHub.Data\Entities\STAR_TFRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STAR.cs
// EduHub.Data\src\EduHub.Data\Entities\STARDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\ST_TFRIO.cs
// EduHub.Data\src\EduHub.Data\Entities\ST_TFRIODataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\ST_TFR.cs
// EduHub.Data\src\EduHub.Data\Entities\ST_TFRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\ST.cs
// EduHub.Data\src\EduHub.Data\Entities\STDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SSHG.cs
// EduHub.Data\src\EduHub.Data\Entities\SSHGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SS.cs
// EduHub.Data\src\EduHub.Data\Entities\SSDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SRAG.cs
// EduHub.Data\src\EduHub.Data\Entities\SRAGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SPWWW.cs
// EduHub.Data\src\EduHub.Data\Entities\SPWWWDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SPU.cs
// EduHub.Data\src\EduHub.Data\Entities\SPUDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SPSMS.cs
// EduHub.Data\src\EduHub.Data\Entities\SPSMSDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SPREPLY.cs
// EduHub.Data\src\EduHub.Data\Entities\SPREPLYDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SPRECIP.cs
// EduHub.Data\src\EduHub.Data\Entities\SPRECIPDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SPOUT.cs
// EduHub.Data\src\EduHub.Data\Entities\SPOUTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SPFSTORE.cs
// EduHub.Data\src\EduHub.Data\Entities\SPFSTOREDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SPFSHARE.cs
// EduHub.Data\src\EduHub.Data\Entities\SPFSHAREDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SPEPRINT.cs
// EduHub.Data\src\EduHub.Data\Entities\SPEPRINTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SPEMRG.cs
// EduHub.Data\src\EduHub.Data\Entities\SPEMRGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SPEMAIL.cs
// EduHub.Data\src\EduHub.Data\Entities\SPEMAILDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SP_REPLY.cs
// EduHub.Data\src\EduHub.Data\Entities\SP_REPLYDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SP_RECIP.cs
// EduHub.Data\src\EduHub.Data\Entities\SP_RECIPDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SMGROUP.cs
// EduHub.Data\src\EduHub.Data\Entities\SMGROUPDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SMCD.cs
// EduHub.Data\src\EduHub.Data\Entities\SMCDDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SMC_TFR.cs
// EduHub.Data\src\EduHub.Data\Entities\SMC_TFRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SMC.cs
// EduHub.Data\src\EduHub.Data\Entities\SMCDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SMAV.cs
// EduHub.Data\src\EduHub.Data\Entities\SMAVDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SMAQ.cs
// EduHub.Data\src\EduHub.Data\Entities\SMAQDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SM.cs
// EduHub.Data\src\EduHub.Data\Entities\SMDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SKGS.cs
// EduHub.Data\src\EduHub.Data\Entities\SKGSDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SK_HRMST.cs
// EduHub.Data\src\EduHub.Data\Entities\SK_HRMSTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SK_HRMS.cs
// EduHub.Data\src\EduHub.Data\Entities\SK_HRMSDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SIRH.cs
// EduHub.Data\src\EduHub.Data\Entities\SIRHDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SIDV.cs
// EduHub.Data\src\EduHub.Data\Entities\SIDVDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SID.cs
// EduHub.Data\src\EduHub.Data\Entities\SIDDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SGTRX.cs
// EduHub.Data\src\EduHub.Data\Entities\SGTRXDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SGSG.cs
// EduHub.Data\src\EduHub.Data\Entities\SGSGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SGSC.cs
// EduHub.Data\src\EduHub.Data\Entities\SGSCDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SGMA.cs
// EduHub.Data\src\EduHub.Data\Entities\SGMADataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SGM.cs
// EduHub.Data\src\EduHub.Data\Entities\SGMDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SGHG.cs
// EduHub.Data\src\EduHub.Data\Entities\SGHGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SGFC.cs
// EduHub.Data\src\EduHub.Data\Entities\SGFCDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SGAM.cs
// EduHub.Data\src\EduHub.Data\Entities\SGAMDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SG.cs
// EduHub.Data\src\EduHub.Data\Entities\SGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SFQA.cs
// EduHub.Data\src\EduHub.Data\Entities\SFQADataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SFAV.cs
// EduHub.Data\src\EduHub.Data\Entities\SFAVDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SFAQ.cs
// EduHub.Data\src\EduHub.Data\Entities\SFAQDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SF.cs
// EduHub.Data\src\EduHub.Data\Entities\SFDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SEC_USR.cs
// EduHub.Data\src\EduHub.Data\Entities\SEC_USRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SEC_URL.cs
// EduHub.Data\src\EduHub.Data\Entities\SEC_URLDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SEC_MSG.cs
// EduHub.Data\src\EduHub.Data\Entities\SEC_MSGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SEC_LLOG.cs
// EduHub.Data\src\EduHub.Data\Entities\SEC_LLOGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SEC_ELOG.cs
// EduHub.Data\src\EduHub.Data\Entities\SEC_ELOGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SDPA.cs
// EduHub.Data\src\EduHub.Data\Entities\SDPADataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SDP.cs
// EduHub.Data\src\EduHub.Data\Entities\SDPDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SDGM.cs
// EduHub.Data\src\EduHub.Data\Entities\SDGMDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SDG.cs
// EduHub.Data\src\EduHub.Data\Entities\SDGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SDFC.cs
// EduHub.Data\src\EduHub.Data\Entities\SDFCDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCSFAG.cs
// EduHub.Data\src\EduHub.Data\Entities\SCSFAGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCSF.cs
// EduHub.Data\src\EduHub.Data\Entities\SCSFDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCL.cs
// EduHub.Data\src\EduHub.Data\Entities\SCLDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCI.cs
// EduHub.Data\src\EduHub.Data\Entities\SCIDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_SVT.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_SVTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_STV.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_STVDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_STE.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_STEDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_ST.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_STDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_SCD.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_SCDDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_RTN.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_RTNDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_RPT.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_RPTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_RFD.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_RFDDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_CVT.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_CVTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_CLV.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_CLVDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_CL.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_CLDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_ASV.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_ASVDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_AST.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_ASTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_ASE.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_ASEDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_APP.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_APPDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_ACV.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_ACVDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_ACL.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_ACLDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCAM.cs
// EduHub.Data\src\EduHub.Data\Entities\SCAMDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCA.cs
// EduHub.Data\src\EduHub.Data\Entities\SCADataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SC.cs
// EduHub.Data\src\EduHub.Data\Entities\SCDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SAP.cs
// EduHub.Data\src\EduHub.Data\Entities\SAPDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SAMA.cs
// EduHub.Data\src\EduHub.Data\Entities\SAMADataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SAM.cs
// EduHub.Data\src\EduHub.Data\Entities\SAMDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SAIM.cs
// EduHub.Data\src\EduHub.Data\Entities\SAIMDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SAII.cs
// EduHub.Data\src\EduHub.Data\Entities\SAIIDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SAI.cs
// EduHub.Data\src\EduHub.Data\Entities\SAIDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SADW.cs
// EduHub.Data\src\EduHub.Data\Entities\SADWDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SADP.cs
// EduHub.Data\src\EduHub.Data\Entities\SADPDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SADAG.cs
// EduHub.Data\src\EduHub.Data\Entities\SADAGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SAD.cs
// EduHub.Data\src\EduHub.Data\Entities\SADDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SACAG.cs
// EduHub.Data\src\EduHub.Data\Entities\SACAGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SABT.cs
// EduHub.Data\src\EduHub.Data\Entities\SABTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SAB.cs
// EduHub.Data\src\EduHub.Data\Entities\SABDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SA.cs
// EduHub.Data\src\EduHub.Data\Entities\SADataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\QSAT.cs
// EduHub.Data\src\EduHub.Data\Entities\QSATDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\QSAG.cs
// EduHub.Data\src\EduHub.Data\Entities\QSAGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\QSAD.cs
// EduHub.Data\src\EduHub.Data\Entities\QSADDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\QSAC.cs
// EduHub.Data\src\EduHub.Data\Entities\QSACDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\QS.cs
// EduHub.Data\src\EduHub.Data\Entities\QSDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\QB.cs
// EduHub.Data\src\EduHub.Data\Entities\QBDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PX_NEW.cs
// EduHub.Data\src\EduHub.Data\Entities\PX_NEWDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PX.cs
// EduHub.Data\src\EduHub.Data\Entities\PXDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PSF.cs
// EduHub.Data\src\EduHub.Data\Entities\PSFDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PSA.cs
// EduHub.Data\src\EduHub.Data\Entities\PSADataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PS.cs
// EduHub.Data\src\EduHub.Data\Entities\PSDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PPS.cs
// EduHub.Data\src\EduHub.Data\Entities\PPSDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PPD.cs
// EduHub.Data\src\EduHub.Data\Entities\PPDDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PN.cs
// EduHub.Data\src\EduHub.Data\Entities\PNDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PML_NEW.cs
// EduHub.Data\src\EduHub.Data\Entities\PML_NEWDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PML.cs
// EduHub.Data\src\EduHub.Data\Entities\PMLDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PLT.cs
// EduHub.Data\src\EduHub.Data\Entities\PLTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PLG.cs
// EduHub.Data\src\EduHub.Data\Entities\PLGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PLC.cs
// EduHub.Data\src\EduHub.Data\Entities\PLCDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PILI.cs
// EduHub.Data\src\EduHub.Data\Entities\PILIDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PI.cs
// EduHub.Data\src\EduHub.Data\Entities\PIDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PGLI.cs
// EduHub.Data\src\EduHub.Data\Entities\PGLIDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PGID.cs
// EduHub.Data\src\EduHub.Data\Entities\PGIDDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PG.cs
// EduHub.Data\src\EduHub.Data\Entities\PGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PF.cs
// EduHub.Data\src\EduHub.Data\Entities\PFDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PETP.cs
// EduHub.Data\src\EduHub.Data\Entities\PETPDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PESP.cs
// EduHub.Data\src\EduHub.Data\Entities\PESPDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PESH.cs
// EduHub.Data\src\EduHub.Data\Entities\PESHDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PEPY.cs
// EduHub.Data\src\EduHub.Data\Entities\PEPYDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PEPUH.cs
// EduHub.Data\src\EduHub.Data\Entities\PEPUHDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PEPU.cs
// EduHub.Data\src\EduHub.Data\Entities\PEPUDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PEPS.cs
// EduHub.Data\src\EduHub.Data\Entities\PEPSDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PEPM.cs
// EduHub.Data\src\EduHub.Data\Entities\PEPMDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PEM.cs
// EduHub.Data\src\EduHub.Data\Entities\PEMDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PELD.cs
// EduHub.Data\src\EduHub.Data\Entities\PELDDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PELA.cs
// EduHub.Data\src\EduHub.Data\Entities\PELADataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PEFH.cs
// EduHub.Data\src\EduHub.Data\Entities\PEFHDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PEF.cs
// EduHub.Data\src\EduHub.Data\Entities\PEFDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PE.cs
// EduHub.Data\src\EduHub.Data\Entities\PEDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PD.cs
// EduHub.Data\src\EduHub.Data\Entities\PDDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PC.cs
// EduHub.Data\src\EduHub.Data\Entities\PCDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\OSCS.cs
// EduHub.Data\src\EduHub.Data\Entities\OSCSDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KUPC.cs
// EduHub.Data\src\EduHub.Data\Entities\KUPCDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KTT.cs
// EduHub.Data\src\EduHub.Data\Entities\KTTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KTRCMP.cs
// EduHub.Data\src\EduHub.Data\Entities\KTRCMPDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KTM.cs
// EduHub.Data\src\EduHub.Data\Entities\KTMDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KTIE.cs
// EduHub.Data\src\EduHub.Data\Entities\KTIEDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KSTREET.cs
// EduHub.Data\src\EduHub.Data\Entities\KSTREETDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KSQ.cs
// EduHub.Data\src\EduHub.Data\Entities\KSQDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KSF.cs
// EduHub.Data\src\EduHub.Data\Entities\KSFDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KSCORE.cs
// EduHub.Data\src\EduHub.Data\Entities\KSCOREDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KSC.cs
// EduHub.Data\src\EduHub.Data\Entities\KSCDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KSA.cs
// EduHub.Data\src\EduHub.Data\Entities\KSADataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KROLE.cs
// EduHub.Data\src\EduHub.Data\Entities\KROLEDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KREPORT.cs
// EduHub.Data\src\EduHub.Data\Entities\KREPORTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KPRMS.cs
// EduHub.Data\src\EduHub.Data\Entities\KPRMSDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KPN.cs
// EduHub.Data\src\EduHub.Data\Entities\KPNDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KPEC.cs
// EduHub.Data\src\EduHub.Data\Entities\KPECDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KPCR.cs
// EduHub.Data\src\EduHub.Data\Entities\KPCRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KPCL.cs
// EduHub.Data\src\EduHub.Data\Entities\KPCLDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KPC.cs
// EduHub.Data\src\EduHub.Data\Entities\KPCDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KNFS.cs
// EduHub.Data\src\EduHub.Data\Entities\KNFSDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KNATT.cs
// EduHub.Data\src\EduHub.Data\Entities\KNATTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KN.cs
// EduHub.Data\src\EduHub.Data\Entities\KNDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KLOG.cs
// EduHub.Data\src\EduHub.Data\Entities\KLOGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGW.cs
// EduHub.Data\src\EduHub.Data\Entities\KGWDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGT.cs
// EduHub.Data\src\EduHub.Data\Entities\KGTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGST.cs
// EduHub.Data\src\EduHub.Data\Entities\KGSTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGR.cs
// EduHub.Data\src\EduHub.Data\Entities\KGRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGO_TFR.cs
// EduHub.Data\src\EduHub.Data\Entities\KGO_TFRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGO.cs
// EduHub.Data\src\EduHub.Data\Entities\KGODataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGLT.cs
// EduHub.Data\src\EduHub.Data\Entities\KGLTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGLSUB.cs
// EduHub.Data\src\EduHub.Data\Entities\KGLSUBDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGLPROG.cs
// EduHub.Data\src\EduHub.Data\Entities\KGLPROGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGLINIT.cs
// EduHub.Data\src\EduHub.Data\Entities\KGLINITDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGL.cs
// EduHub.Data\src\EduHub.Data\Entities\KGLDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGH.cs
// EduHub.Data\src\EduHub.Data\Entities\KGHDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGG.cs
// EduHub.Data\src\EduHub.Data\Entities\KGGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGD.cs
// EduHub.Data\src\EduHub.Data\Entities\KGDDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGCV.cs
// EduHub.Data\src\EduHub.Data\Entities\KGCVDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGCHI.cs
// EduHub.Data\src\EduHub.Data\Entities\KGCHIDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGC.cs
// EduHub.Data\src\EduHub.Data\Entities\KGCDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KFTC.cs
// EduHub.Data\src\EduHub.Data\Entities\KFTCDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KERROR.cs
// EduHub.Data\src\EduHub.Data\Entities\KERRORDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KEMA.cs
// EduHub.Data\src\EduHub.Data\Entities\KEMADataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KDO.cs
// EduHub.Data\src\EduHub.Data\Entities\KDODataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KDI.cs
// EduHub.Data\src\EduHub.Data\Entities\KDIDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KDELETE.cs
// EduHub.Data\src\EduHub.Data\Entities\KDELETEDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCY.cs
// EduHub.Data\src\EduHub.Data\Entities\KCYDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCV.cs
// EduHub.Data\src\EduHub.Data\Entities\KCVDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCT.cs
// EduHub.Data\src\EduHub.Data\Entities\KCTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCR.cs
// EduHub.Data\src\EduHub.Data\Entities\KCRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCPC.cs
// EduHub.Data\src\EduHub.Data\Entities\KCPCDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCOHORT.cs
// EduHub.Data\src\EduHub.Data\Entities\KCOHORTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCM_TFR.cs
// EduHub.Data\src\EduHub.Data\Entities\KCM_TFRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCM.cs
// EduHub.Data\src\EduHub.Data\Entities\KCMDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCI.cs
// EduHub.Data\src\EduHub.Data\Entities\KCIDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCD_TFR.cs
// EduHub.Data\src\EduHub.Data\Entities\KCD_TFRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCD.cs
// EduHub.Data\src\EduHub.Data\Entities\KCDDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCC.cs
// EduHub.Data\src\EduHub.Data\Entities\KCCDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCB.cs
// EduHub.Data\src\EduHub.Data\Entities\KCBDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KBPT.cs
// EduHub.Data\src\EduHub.Data\Entities\KBPTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KBP.cs
// EduHub.Data\src\EduHub.Data\Entities\KBPDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KBANK.cs
// EduHub.Data\src\EduHub.Data\Entities\KBANKDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KAP.cs
// EduHub.Data\src\EduHub.Data\Entities\KAPDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KAM.cs
// EduHub.Data\src\EduHub.Data\Entities\KAMDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KADM.cs
// EduHub.Data\src\EduHub.Data\Entities\KADMDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KAD.cs
// EduHub.Data\src\EduHub.Data\Entities\KADDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KABN.cs
// EduHub.Data\src\EduHub.Data\Entities\KABNDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KAB.cs
// EduHub.Data\src\EduHub.Data\Entities\KABDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\GLPREV.cs
// EduHub.Data\src\EduHub.Data\Entities\GLPREVDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\GLFPREV.cs
// EduHub.Data\src\EduHub.Data\Entities\GLFPREVDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\GLFBUDG.cs
// EduHub.Data\src\EduHub.Data\Entities\GLFBUDGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\GLFBANK.cs
// EduHub.Data\src\EduHub.Data\Entities\GLFBANKDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\GLF.cs
// EduHub.Data\src\EduHub.Data\Entities\GLFDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\GLCFPREV.cs
// EduHub.Data\src\EduHub.Data\Entities\GLCFPREVDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\GLCF.cs
// EduHub.Data\src\EduHub.Data\Entities\GLCFDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\GLBUDG.cs
// EduHub.Data\src\EduHub.Data\Entities\GLBUDGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\GLBANK.cs
// EduHub.Data\src\EduHub.Data\Entities\GLBANKDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\GL.cs
// EduHub.Data\src\EduHub.Data\Entities\GLDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\FINHIST.cs
// EduHub.Data\src\EduHub.Data\Entities\FINHISTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\FER_FDT.cs
// EduHub.Data\src\EduHub.Data\Entities\FER_FDTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\FDT_IMP.cs
// EduHub.Data\src\EduHub.Data\Entities\FDT_IMPDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\FDT_EXP.cs
// EduHub.Data\src\EduHub.Data\Entities\FDT_EXPDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\DRF.cs
// EduHub.Data\src\EduHub.Data\Entities\DRFDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\DRB.cs
// EduHub.Data\src\EduHub.Data\Entities\DRBDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\DR.cs
// EduHub.Data\src\EduHub.Data\Entities\DRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\DFVT.cs
// EduHub.Data\src\EduHub.Data\Entities\DFVTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\DFHI.cs
// EduHub.Data\src\EduHub.Data\Entities\DFHIDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\DFF.cs
// EduHub.Data\src\EduHub.Data\Entities\DFFDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\DFB.cs
// EduHub.Data\src\EduHub.Data\Entities\DFBDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\DF_TFR.cs
// EduHub.Data\src\EduHub.Data\Entities\DF_TFRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\DF.cs
// EduHub.Data\src\EduHub.Data\Entities\DFDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\CRTT.cs
// EduHub.Data\src\EduHub.Data\Entities\CRTTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\CRFTC.cs
// EduHub.Data\src\EduHub.Data\Entities\CRFTCDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\CRF.cs
// EduHub.Data\src\EduHub.Data\Entities\CRFDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\CR.cs
// EduHub.Data\src\EduHub.Data\Entities\CRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\BPAY_DAT.cs
// EduHub.Data\src\EduHub.Data\Entities\BPAY_DATDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\BKHR.cs
// EduHub.Data\src\EduHub.Data\Entities\BKHRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\BKH.cs
// EduHub.Data\src\EduHub.Data\Entities\BKHDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\BANKSIG.cs
// EduHub.Data\src\EduHub.Data\Entities\BANKSIGDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\ARF.cs
// EduHub.Data\src\EduHub.Data\Entities\ARFDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\AR.cs
// EduHub.Data\src\EduHub.Data\Entities\ARDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\AKT.cs
// EduHub.Data\src\EduHub.Data\Entities\AKTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\AKR.cs
// EduHub.Data\src\EduHub.Data\Entities\AKRDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\AKL.cs
// EduHub.Data\src\EduHub.Data\Entities\AKLDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\AKK.cs
// EduHub.Data\src\EduHub.Data\Entities\AKKDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\AKD.cs
// EduHub.Data\src\EduHub.Data\Entities\AKDDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\AKCT.cs
// EduHub.Data\src\EduHub.Data\Entities\AKCTDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\AKC.cs
// EduHub.Data\src\EduHub.Data\Entities\AKCDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\AKB.cs
// EduHub.Data\src\EduHub.Data\Entities\AKBDataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\A_DECRYP.cs
// EduHub.Data\src\EduHub.Data\Entities\A_DECRYPDataSet.cs
