
// Generated helper templates
// Generated items
// EduHub.Data\src\EduHub.Data\Entities\UM_TFR_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\UM_TFR_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\UM_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\UM_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TXHG_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TXHG_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TXAS_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TXAS_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TTTG_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TTTG_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TTEX_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TTEX_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TTES_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TTES_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TTEP_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TTEP_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TTEI_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TTEI_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TTEF_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TTEF_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TRSTACC_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TRSTACC_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TRPROUT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TRPROUT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TRPMODE_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TRPMODE_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\THTQ_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\THTQ_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\THTN_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\THTN_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TH_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TH_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TETN_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TETN_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TETE_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TETE_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TEC_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TEC_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TE_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TE_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TCTR_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TCTR_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TCTQ_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TCTQ_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TCTD_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TCTD_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TCTB_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TCTB_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TCAT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TCAT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\TC_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\TC_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SXHI_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SXHI_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SXAS_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SXAS_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SXABCONV_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SXABCONV_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SXAB_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SXAB_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SVAG_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SVAG_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SUPR_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SUPR_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SUBL_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SUBL_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SU_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SU_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STVDO_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\STVDO_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STVDI_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\STVDI_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STTRIPS_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\STTRIPS_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STSP_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\STSP_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STSB_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\STSB_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STRE_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\STRE_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STRA_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\STRA_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STPT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\STPT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STPO_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\STPO_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STMB_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\STMB_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STMA_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\STMA_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\STBT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\STBT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\ST_TFRIO_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\ST_TFRIO_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\ST_TFR_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\ST_TFR_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\ST_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\ST_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SSHG_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SSHG_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SS_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SS_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SRAG_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SRAG_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SPU_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SPU_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SPOUT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SPOUT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SPEPRINT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SPEPRINT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SPEMAIL_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SPEMAIL_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SMGROUP_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SMGROUP_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SMCD_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SMCD_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SMC_TFR_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SMC_TFR_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SMC_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SMC_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SMAV_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SMAV_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SMAQ_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SMAQ_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SM_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SM_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SKGS_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SKGS_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SK_HRMST_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SK_HRMST_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SK_HRMS_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SK_HRMS_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SIRH_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SIRH_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SIDV_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SIDV_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SID_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SID_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SGTRX_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SGTRX_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SGSG_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SGSG_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SGSC_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SGSC_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SGMA_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SGMA_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SGM_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SGM_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SGHG_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SGHG_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SGAM_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SGAM_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SG_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SG_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SFQA_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SFQA_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SFAV_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SFAV_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SFAQ_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SFAQ_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SF_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SF_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SEC_USR_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SEC_USR_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SEC_URL_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SEC_URL_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SEC_MSG_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SEC_MSG_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SEC_LLOG_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SEC_LLOG_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SEC_ELOG_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SEC_ELOG_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SDPA_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SDPA_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SDP_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SDP_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SDGM_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SDGM_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SDG_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SDG_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SDFC_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SDFC_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCSFAG_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCSFAG_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCSF_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCSF_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCL_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCL_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCI_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCI_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_SVT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_SVT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_STV_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_STV_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_STE_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_STE_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_ST_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_ST_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_SCD_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_SCD_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_RTN_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_RTN_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_RPT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_RPT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_RFD_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_RFD_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_CVT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_CVT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_CLV_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_CLV_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_CL_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_CL_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_ASV_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_ASV_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_AST_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_AST_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_ASE_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_ASE_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_APP_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_APP_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_ACV_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_ACV_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_ACL_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCEN_ACL_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCAM_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCAM_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SCA_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SCA_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SC_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SC_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SAP_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SAP_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SAMA_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SAMA_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SAM_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SAM_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SAIM_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SAIM_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SAII_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SAII_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SAI_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SAI_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SADW_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SADW_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SADP_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SADP_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SADAG_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SADAG_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SAD_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SAD_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SACAG_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SACAG_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SABT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SABT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SAB_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SAB_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\SA_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\SA_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\QS_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\QS_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\QB_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\QB_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PX_NEW_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PX_NEW_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PX_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PX_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PSF_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PSF_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PSA_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PSA_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PS_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PS_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PPS_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PPS_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PPD_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PPD_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PN_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PN_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PML_NEW_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PML_NEW_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PML_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PML_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PLT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PLT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PLG_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PLG_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PLC_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PLC_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PILI_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PILI_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PI_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PI_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PG_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PG_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PF_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PF_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PETP_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PETP_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PESP_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PESP_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PESH_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PESH_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PEPY_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PEPY_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PEPUH_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PEPUH_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PEPU_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PEPU_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PEPS_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PEPS_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PEPM_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PEPM_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PEM_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PEM_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PELD_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PELD_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PELA_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PELA_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PEFH_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PEFH_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PEF_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PEF_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PE_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PE_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PD_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PD_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\PC_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\PC_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\OSCS_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\OSCS_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KTRCMP_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KTRCMP_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KTIE_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KTIE_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KSQ_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KSQ_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KSI_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KSI_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KSF_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KSF_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KSC_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KSC_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KSA_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KSA_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KROLE_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KROLE_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KREPORT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KREPORT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KPRMS_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KPRMS_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KPN_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KPN_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KPEC_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KPEC_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KPCR_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KPCR_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KPCL_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KPCL_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KPC_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KPC_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KNFS_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KNFS_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KN_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KN_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KLOG_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KLOG_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGW_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KGW_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KGT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGST_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KGST_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGR_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KGR_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGLT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KGLT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGLSUB_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KGLSUB_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGLPROG_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KGLPROG_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGLINIT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KGLINIT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGL_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KGL_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGH_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KGH_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGG_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KGG_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGD_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KGD_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGCHI_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KGCHI_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KGC_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KGC_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KFTC_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KFTC_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KERROR_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KERROR_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KEMA_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KEMA_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KDO_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KDO_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KDI_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KDI_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KDELETE_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KDELETE_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCY_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KCY_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCV_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KCV_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KCT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCR_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KCR_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCOHORT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KCOHORT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCM_TFR_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KCM_TFR_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCM_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KCM_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCI_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KCI_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCD_TFR_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KCD_TFR_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCD_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KCD_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCC_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KCC_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KCB_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KCB_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KBPT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KBPT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KBP_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KBP_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KBANK_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KBANK_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KAP_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KAP_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KAM_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KAM_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KADM_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KADM_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KAD_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KAD_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\KAB_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\KAB_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\GLPREV_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\GLPREV_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\GLFPREV_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\GLFPREV_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\GLFBUDG_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\GLFBUDG_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\GLFBANK_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\GLFBANK_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\GLF_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\GLF_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\GLCFPREV_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\GLCFPREV_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\GLCF_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\GLCF_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\GLBUDG_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\GLBUDG_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\GLBANK_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\GLBANK_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\GL_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\GL_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\FINHIST_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\FINHIST_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\FER_FDT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\FER_FDT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\FDT_IMP_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\FDT_IMP_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\FDT_EXP_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\FDT_EXP_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\DRF_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\DRF_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\DR_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\DR_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\DFVT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\DFVT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\DFHI_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\DFHI_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\DFF_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\DFF_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\DFB_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\DFB_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\DF_TFR_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\DF_TFR_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\DF_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\DF_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\CRFTC_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\CRFTC_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\CRF_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\CRF_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\CR_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\CR_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\BPAY_DAT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\BPAY_DAT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\BKHR_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\BKHR_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\BKH_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\BKH_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\ARF_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\ARF_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\AR_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\AR_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\AKT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\AKT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\AKR_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\AKR_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\AKL_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\AKL_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\AKK_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\AKK_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\AKD_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\AKD_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\AKCT_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\AKCT_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\AKC_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\AKC_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\AKB_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\AKB_DataSet.cs
// EduHub.Data\src\EduHub.Data\Entities\A_DECRYP_Entity.cs
// EduHub.Data\src\EduHub.Data\Entities\A_DECRYP_DataSet.cs
