<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net452;net10.0</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<Configurations>Debug;Release;Scoped</Configurations>
		<Title>eduHub Data Samples</Title>
		<Product>eduHub</Product>
		<Copyright>Copyright © Gary Sharp 2019</Copyright>
		<AssemblyVersion>1.0.4.0</AssemblyVersion>
		<FileVersion>1.0.4.0</FileVersion>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Scoped|AnyCPU'">
		<OutputPath>bin\Scoped\</OutputPath>
		<Optimize>true</Optimize>
	</PropertyGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net452'">
		<Reference Include="System.IO.Compression" />
		<Reference Include="System.Data.DataSetExtensions" />
		<Reference Include="Microsoft.CSharp" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\EduHub.Data\EduHub.Data.csproj" />
	</ItemGroup>
</Project>